apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserver-ingress
spec:
  tls:
    - hosts:
        - niennienzz-httpserver.com
      secretName: tsl-secret
  rules:
    - host: niennienzz-httpserver.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpserver-service
                port:
                  number: 8080